### PR TITLE
Client connection freezes and resends are missing when servers restart on heavy load

### PR DESCRIPTION
**Pull request by ihsandemir**
Fixes the problems with client hanging during server restarts on heavy loads. Fixes a memory access issue when re-throwing an exception, correctly clears the call promise maps during connection close.

Partially fixes the issue reported at https://github.com/hazelcast/hazelcast-cpp-client/issues/64 .

### CODE REVIEW

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by sancar** [comment]
:+1:

**Pull request merged**
