### PR TITLE
fenced_lock proxy should release the sessions in case of exceptions

### PR DESCRIPTION
**Pull request by ihsandemir**
fenced_lock should release the sessions in case of exceptions in order to not leak session resources.

backport from https://github.com/hazelcast/hazelcast/pull/17697

### CODE REVIEW

**Review by sancar — APPROVED** [review]

**Comment by ihsandemir** [comment]
verify-windows

**Review by yemreinci — APPROVED** [review]

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify-windows

**Pull request merged**
