### PR TITLE
Update dependency:get command to latest syntax

### PR DESCRIPTION
**Pull request by JackPGreen**
When running `scripts/test-unix.sh`, the following error is produced:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.6.0:get (default-cli) on project standalone-pom: Couldn't download artifact: The following artifacts could not be resolved: com.hazelcast:hazelcast-remote-controller:jar:0.8-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-remote-controller:jar:0.8-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Failed download remote-controller jar com.hazelcast:hazelcast-remote-controller:0.8-SNAPSHOT
```

`hazelcast-remote-controller` is being downloaded via `mvn dependency:get -DrepoUrl=${SNAPSHOT_REPO}`

The `repoUrl` parameter was deprecated in favour of `remoteRepositories` in `maven-dependency-plugin` [2.4](https://maven.apache.org/plugins-archives/maven-dependency-plugin-2.4/get-mojo.html) (released 2011) and removed in [3.0.2](https://maven.apache.org/plugins-archives/maven-dependency-plugin-3.0.2/get-mojo.html) (released 2017).

I've:
- updated the command to use the new parameter
- fixed `maven-dependency-plugin` at the latest (`3.6.0`) to ensure repeatable builds - otherwise the version is decided based on the Maven version which is environment-dependent

### CODE REVIEW

**Review by avtarraikmo — APPROVED** [review]
https://maven.apache.org/plugins/maven-dependency-plugin/get-mojo.html#remoteRepositories

Changed in 3.6.0+

**Review by ihsandemir — DISMISSED** [review]

**Comment by JackPGreen** [comment]
[Build issues are unrelated to this change](https://hazelcast.slack.com/archives/C022RC6LVPY/p1692120783252489).

**Comment by JackPGreen** [comment]
Reopen

**Comment by ihsandemir** [comment]
The [merged PR](https://github.com/hazelcast/hazelcast-cpp-client/pull/1216) already fixed the issue. Let me know if anything still missing.

**Pull request closed without merging**
