### PR TITLE
Implement write/readUTFArray methods for PortableWriter/PortableReader

### LINKED ISSUE #224: Add write/readUTFArray interface to Portable Writer/Reader
Portable writer/reader is missing the write and read UTF array which exis at Java API (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/nio/serialization/PortableReader.java#L191 https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/nio/serialization/PortableWriter.java#L208)

### PR DESCRIPTION
**Pull request by RikeVoltz**
This PR closes #224

### CODE REVIEW

**Comment by RikeVoltz** [comment]
Whoops, my bad, I haven't seen already submitted PR, that fixes the same issue. Should I close this one in favor of #303?

**Comment by ihsandemir** [comment]
> Whoops, my bad, I haven't seen already submitted PR, that fixes the same issue. Should I close this one in favor of #303?

Hello @RikeVoltz I asked the other PR submitter to update the PR https://github.com/hazelcast/hazelcast-cpp-client/pull/303#issuecomment-630028009 If he responds, then he can continue and we can close this PR, otherwise we can merge you PR.

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
Test failures:

windows:
```
Test Name | Duration | Age
-- | -- | --
ClientMapTestWithDifferentConfigs/ClientMapTest.testValuesWithPagingPredicate/0 (816-byte object <10-69 8E-02 64-65 76-00 26-53 33-6F 88-8A 8E-02 EE-C5 00-00 03-00 00-00 0F-00 00-00 90-6C 8E-02 64-65 76-2D 70-61 73-73 00-00 00-00 78-E2 18-02 08-00 00-00 0F-00 00-00 00-CD CD-CD 0F-00 00-00 ... CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD FF-FF FF-FF 00-00 00-00 84-EA 9F-01 00-00 00-00 E0-74 8E-02 00-E5 18-02 9A-8E FC-B8 B8-F5 18-02 97-49 90-01 00-00 00-00 0F-00 00-00 32-00 00-00>) | 0.25 sec | 1
ClientMapTestWithDifferentConfigs/ClientMapTest.testValuesWithPagingPredicate/1 (816-byte object <38-6D 8E-02 64-65 76-00 26-53 33-6F 30-76 8E-02 26-C2 00-00 03-00 00-00 0F-00 00-00 A0-68 8E-02 64-65 76-2D 70-61 73-73 00-00 00-00 B0-E5 18-02 08-00 00-00 0F-00 00-00 00-CD CD-CD 0F-00 00-00 ... CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD FF-FF FF-FF 00-00 00-00 84-EA 9F-01 00-00 00-00 F0-70 8E-02 00-E8 18-02 52-83 FC-B8 B8-F5 18-02 A7-4A 90-01 00-00 00-00 0F-00 00-00 32-00 00-00>) | 0.23 sec | 1
ClientMapTestWithDifferentConfigs/ClientMapTest.testValuesWithPagingPredicate/2 (816-byte object <88-6E 8E-02 64-65 76-00 CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC 03-00 00-00 0F-00 00-00 C0-6E 8E-02 64-65 76-2D 70-61 73-73 00-CC CC-CC CC-CC CC-CC 08-00 00-00 0F-00 00-00 00-CD CD-CD 0F-00 00-00 ... CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD FF-FF FF-FF 00-00 00-00 84-EA 9F-01 00-00 00-00 68-6F 8E-02 00-EC 18-02 10-24 30-6F F2-62 B8-BA FE-FF FF-FF 00-00 00-00 0F-00 00-00 32-00 00-00>) | 0.21 sec | 1
ClientMapTestWithDifferentConfigs/ClientMapTest.testEntrySetWithPagingPredicate/0 (816-byte object <90-63 91-02 64-65 76-00 26-53 33-6F 40-15 86-02 EE-C5 00-00 03-00 00-00 0F-00 00-00 30-5F 91-02 64-65 76-2D 70-61 73-73 00-00 00-00 78-E2 18-02 08-00 00-00 0F-00 00-00 00-CD CD-CD 0F-00 00-00 ... CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD FF-FF FF-FF 00-00 00-00 84-EA 9F-01 00-00 00-00 A0-66 91-02 00-E5 18-02 9A-8E FC-B8 B8-F5 18-02 97-49 90-01 00-00 00-00 0F-00 00-00 32-00 00-00>) | 0.17 sec | 1
ClientMapTestWithDifferentConfigs/ClientMapTest.testEntrySetWithPagingPredicate/1 (816-byte object <C0-5E 91-02 64-65 76-00 26-53 33-6F F0-71 88-02 26-C2 00-00 03-00 00-00 0F-00 00-00 38-5D 91-02 64-65 76-2D 70-61 73-73 00-00 00-00 B0-E5 18-02 08-00 00-00 0F-00 00-00 00-CD CD-CD 0F-00 00-00 ... CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD FF-FF FF-FF 00-00 00-00 84-EA 9F-01 00-00 00-00 B8-6E 91-02 00-E8 18-02 52-83 FC-B8 B8-F5 18-02 A7-4A 90-01 00-00 00-00 0F-00 00-00 32-00 00-00>) | 0.17 sec | 1
ClientMapTestWithDifferentConfigs/ClientMapTest.testEntrySetWithPagingPredicate/2 (816-byte object <28-61 91-02 64-65 76-00 CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC 03-00 00-00 0F-00 00-00 60-61 91-02 64-65 76-2D 70-61 73-73 00-CC CC-CC CC-CC CC-CC 08-00 00-00 0F-00 00-00 00-CD CD-CD 0F-00 00-00 ... CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD CD-CD FF-FF FF-FF 00-00 00-00 84-EA 9F-01 00-00 00-00 C0-6C 91-02 00-EC 18-02 10-24 30-6F F2-62 B8-BA FE-FF FF-FF 00-00 00-00 0F-00 00-00 32-00 00-00>) | 0.2 sec | 1
```

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
Merging this PR since there is no response to https://github.com/hazelcast/hazelcast-cpp-client/pull/303#issuecomment-630028009. Closing the other PR.

**Pull request merged**
