### PR TITLE
Client does not shut down properly when cluster connection attempts all fail

### PR DESCRIPTION
**Pull request by ihsandemir**
Fix for shutting down the client properly if the cluster connection attempts all fail.

### CODE REVIEW

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by sancar** [comment]
I did not get why shutdown needs a countdown latch to wait. 
Can you describe failing scenario ? 
First thing comes to my mind that a thread called shutdown and running shutdown method. In the meantime, destructor called shutdown. Checked that it is not active and returned immediately causing to delete everything while another thread accessing the fields of it. 
But in this scenario, it means that HazelcastInstance shared among threads without a sharedPtr. 

I am trying to understand if this is a problem we need to solve, or is it just a illegal usage.

**Comment by ihsandemir** [comment]
@sancar Yes, that is exactly the case. I saw it test https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/test/src/cluster/ClientConnectionTest.cpp#L48

So, the test finishes and hence the client destructor is executed before the shutdown is actually completed and hence during the shutdown illegal memory access occurs. I don't think it is an illegal use. 

Yes, java uses shared references which eliminates the problem. It may also be solved by keeping an internally shared pointer and just returning a wrapper object HazelcastClient to the user, and also keeping a reference inside the clientcontext object which is being used between the threads. 

In any case, we need to guarantee that the shutdown is finished and all threads are closed before exiting the destructor.

**Comment by sancar** [comment]
I still don't get it. How is the HazelcastClient shared between two threads in this test? If it is a raw pointer and one is calling destructor. This usage is illegal. 
If it was shared via a shared_ptr<HazelcastCLient> then since the one calling shutdown is not decremented the shared_ptr count, no one can call destructor before it finishes.

**Comment by ihsandemir** [comment]
@sancar Scenario: ClusterListenerThread at this line: https://github.com/ihsandemir/hazelcast-cpp-client/blob/shutdownFix/hazelcast/src/hazelcast/client/connection/ClusterListenerThread.cpp#L88
and HazelcastClient passes this line: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/src/hazelcast/client/HazelcastClient.cpp#L56

But I think I can also fix it by changing the lines 87 and 88 https://github.com/ihsandemir/hazelcast-cpp-client/blob/shutdownFix/hazelcast/src/hazelcast/client/connection/ClusterListenerThread.cpp#L87 .

**Comment by ihsandemir** [comment]
verify

**Pull request merged**
