### PR TITLE
Update Hazelcast documentation link version

### PR DESCRIPTION
**Pull request by JackPGreen**
Replace any references to `https://docs.hazelcast.com/hazelcast/5.x` with `https://docs.hazelcast.com/hazelcast/latest`

### CODE REVIEW

**Review by ihsandemir — APPROVED** [review]

**Comment by JackPGreen** [comment]
verify

**Comment by JackPGreen** [comment]
I don't think the build failures are related to my change - https://hazelcast.slack.com/archives/C022RC6LVPY/p1691397977159399

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by JackPGreen** [comment]
Reopen

**Review by ihsandemir — COMMENTED** [review]
why are you changing single quote to double quote? is that really needed?

**Comment by JackPGreen** [comment]
> why are you changing single quote to double quote? is that really needed?

Not sure what happened there, amended to the (single) file changed.

**Review by ihsandemir — APPROVED** [review]

**Pull request merged**
