### PR TITLE
camelCase to snake_case conversion

### PR DESCRIPTION
**Pull request by ihsandemir**
In this PR, I converted the API from camelCase to snake_case which is more used at the C/C++ community. The file names changes in the same way. 

The API is basically the same. The only name changes are:
    - Removed namespace cluster.
    - Moved `member_selector` to hazelcast::client namespace.
    - renamed `client` to `local_endpoint`.

All the rest API changes are just naming case change.

An example command used for changing method cases is:

`run-clang-tidy.py -fix -header-filter='.*' -checks='-*,readability-identifier-naming' -config="{CheckOptions: [ {key: readability-identifier-naming.PublicMemberCase, value: lower_case} ]}"`

Added `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` cmake flag on cmake build locally on my machine to produce the compilation database `compile_commands.json` for the script to find the files properly.

fixes https://github.com/hazelcast/hazelcast-cpp-client/issues/663

### CODE REVIEW

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify-linux

**Comment by sancar** [comment]
How about we just remove `cluster` namespace ? I just take a look and it seems there is not much usage of it anyway. For example, cluster service is not under `cluster` namespace.

**Comment by sancar** [comment]
Hazelcast.h still starts with capital letters. Is that intentional? Seems odd between others.

**Comment by sancar** [comment]
We have `hz_client` and `hazelcast_client` seems difficult to separate. 
Should we rename `hz_client` to something like `client_endpoint`

**Comment by ihsandemir** [comment]
> How about we just remove `cluster` namespace ? I just take a look and it seems there is not much usage of it anyway. For example, cluster service is not under `cluster` namespace.

It was left over, changed it.

**Review by sancar — APPROVED** [review]

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify-linux

**Comment by sancar** [comment]
👍

**Pull request merged**
