### PR TITLE
Fix missing version change during release of 3.6.3

### PR DESCRIPTION
**Pull request by ihsandemir**
The release process script was missing a step to change these versions (happened during releasing 3.6.3). The release devops script will be separately fixed to do this in the future releases. This PR fixes the missing change for the cpp repo.

### CODE REVIEW

**Comment by hasancelik** [comment]
👍

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Pull request merged**
