### PR TITLE
Incorrect HZ version used during release verification for maintenance 

### PR DESCRIPTION
**Pull request by ihsandemir**
Changing the version in maintenance from 3.7 to 3.6.1.

### CODE REVIEW

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
verify

**Comment by sancar** [comment]
:+1:

**Comment by hasancelik** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Pull request merged**
