### PR TITLE
Replace NULL keyword to nullptr to modernize as C++ style

### PR DESCRIPTION
**Pull request by cngzhnp**

### CODE REVIEW

**Comment by OzanCansel** [comment]
@cngzhnp  Could you remove changes at `RemoteController.cpp` and ``remote_controller_types.cpp` since they are generated code, so we don't modify those classes.

**Review by OzanCansel — CHANGES_REQUESTED** [review]
@cngzhnp Could you remove changes at `RemoteController.cpp` and `remote_controller_types.cpp` since they are generated code, so we don't modify those classes.

**Comment by OzanCansel** [comment]
verify

**Comment by cngzhnp** [comment]
@OzanCansel Thanks for the review, I just reverted back changes on generated source files.

**Pull request closed without merging**
