### PR TITLE
Googletest framework adoption

### PR DESCRIPTION
**Pull request by ihsandemir**
The tests are switched to the Googletest framework. This shall allow us more testing features in addition to the ability to be able to publish test results into Jenkins.

I had to commit googletest framework since the gcc 3.4 does not support -Wno-missing-field-initializers flag which is used by googletest cmake. I opened an issue for that (https://github.com/google/googletest/issues/695). If this is resolved, then we may be able to remove the code for googletest by introducing googletest as an external cmake project (https://cmake.org/cmake/help/v3.0/module/ExternalProject.html).  Commented out the /MT flag in googletest/cmake/internal_utils.cmake for fixing the cross DLL boundary memory allocation/deallocation related problems).

The googletest is used as a submodule which uses the code at the forked googletest repository https://github.com/ihsandemir/googletest/tree/hazelcasttest . The pre-mentioned changes are committed in this repository. 

Also added the HZ_BUILD_TESTS and HZ_BUILD_EXAMPLES cmake flags for optionally enabling the builds for tests and examples.

### CODE REVIEW

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-windows

**Comment by sancar** [comment]
:+1:

**Comment by hasancelik** [comment]
verify

**Comment by hasancelik** [comment]
verify-linux

**Comment by hasancelik** [comment]
verify

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verıfy-linux

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-linux

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify-windows

**Comment by ihsandemir** [comment]
verify-windows

**Comment by hasancelik** [comment]
verify

**Pull request merged**
