### PR TITLE
Added missing less operator for HazelcastJsonValue, fixed necessity of empty default constructor of HazelcastJsonValue

### LINKED ISSUE #589: Missing default ctor for HazelcastJsonValue
C++ compiler version: gcc 9.3
Hazelcast Cpp client version: 3.12
Hazelcast server version: 3.12
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 3
OS version (Windows/Linux/OSX): Linux Ubuntu 20.04

#### Expected behaviour
`.values()` method for `IMap<std::string, HazelcastJsonValue>` with no arguments compiles successfully and produce correct output(all values in the map)

#### Actual behaviour
```stacktrace
/usr/include/c++/9/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = hazelcast::client::HazelcastJsonValue; _Args = {}]’:
/usr/include/c++/9/bits/stl_uninitialized.h:545:18:   required from ‘static _ForwardIterator std::__uninitialized_default_n_1<_TrivialValueType>::__uninit_default_n(_ForwardIterator, _Size) [with _ForwardIterator = hazelcast::client::HazelcastJsonValue*; _Size = long unsigned int; bool _TrivialValueType = false]’
/usr/include/c++/9/bits/stl_uninitialized.h:601:20:   required from ‘_ForwardIterator std::__uninitialized_default_n(_ForwardIterator, _Size) [with _ForwardIterator = hazelcast::client::HazelcastJsonValue*; _Size = long unsigned int]’
/usr/include/c++/9/bits/stl_uninitialized.h:663:44:   required from ‘_ForwardIterator std::__uninitialized_default_n_a(_ForwardIterator, _Size, std::allocator<_Tp>&) [with _ForwardIterator = hazelcast::client::HazelcastJsonValue*; _Size = long unsigned int; _Tp = hazelcast::client::HazelcastJsonValue]’
/usr/include/c++/9/bits/stl_vector.h:1603:36:   required from ‘void std::vector<_Tp, _Alloc>::_M_default_initialize(std::vector<_Tp, _Alloc>::size_type) [with _Tp = hazelcast::client::HazelcastJsonValue; _Alloc = std::allocator<hazelcast::client::HazelcastJsonValue>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/9/bits/stl_vector.h:509:9:   required from ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const allocator_type&) [with _Tp = hazelcast::client::HazelcastJsonValue; _Alloc = std::allocator<hazelcast::client::HazelcastJsonValue>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<hazelcast::client::HazelcastJsonValue>]’
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/map/ClientMapProxy.h:751:36:   required from ‘std::vector<V> hazelcast::client::map::ClientMapProxy<K, V>::values() [with K = std::__cxx11::basic_string<char>; V = hazelcast::client::HazelcastJsonValue]’
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/IMap.h:603:40:   required from ‘std::vector<V> hazelcast::client::IMap<K, V>::values() [with K = std::__cxx11::basic_string<char>; V = hazelcast::client::HazelcastJsonValue]’
/home/rikevoltz/work/Projects/hazelcast_tests/main.cpp:22:34:   required from here
/usr/include/c++/9/bits/stl_construct.h:75:7: error: no matching function for call to ‘hazelcast::client::HazelcastJsonValue::HazelcastJsonValue()’
   75 |     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/rikevoltz/work/Projects/hazelcast_tests/main.cpp:2:
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/HazelcastJsonValue.h:58:13: note: candidate: ‘hazelcast::client::HazelcastJsonValue::HazelcastJsonValue(const string&)’
   58 |             HazelcastJsonValue(const std::string &jsonString);
      |             ^~~~~~~~~~~~~~~~~~
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/HazelcastJsonValue.h:58:13: note:   candidate expects 1 argument, 0 provided
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/HazelcastJsonValue.h:48:29: note: candidate: ‘hazelcast::client::HazelcastJsonValue::HazelcastJsonValue(const hazelcast::client::HazelcastJsonValue&)’
   48 |         class HAZELCAST_API HazelcastJsonValue {
      |                             ^~~~~~~~~~~~~~~~~~
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/HazelcastJsonValue.h:48:29: note:   candidate expects 1 argument, 0 provided
```
As I understand correctly, the default ctor for HazelcastJsonValue is missing
#### Steps to reproduce the behaviour
```c++
  auto client = hazelcast::client::HazelcastClient{config};
  auto some_map = client.getMap<std::string, HazelcastJsonValue>("test_map");
  some_map.put("some_key", HazelcastJsonValue("{\"id\":\"some_id\"}"));
  some_map.put("some_other_key", HazelcastJsonValue("{\"id\":\"some_other_id\"}"));
  some_map.put("another_key", HazelcastJsonValue("{\"id\":\"another_id\"}"));
  auto results = some_map.values();
```

### LINKED ISSUE #590: Missing operator< for HazelcastJsonValue
C++ compiler version: gcc 9.3
Hazelcast Cpp client version: 3.12
Hazelcast server version: 3.12
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 3
OS version (Windows/Linux/OSX): Linux Ubuntu 20.04

Please attach relevant logs and files for client and server side.

#### Expected behaviour
`.values(PagingPredicate(n))` method for `IMap<std::string, HazelcastJsonValue>` compiles successfully and produce correct output(first n values in the map)

#### Actual behaviour
```
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/impl/LazyEntryArrayImpl.h: In instantiation of ‘bool hazelcast::client::impl::LazyEntryArrayImpl<K, V>::Item::operator<(const hazelcast::client::impl::LazyEntryArrayImpl<K, V>::Item&) const [with K = std::__cxx11::basic_string<char>; V = hazelcast::client::HazelcastJsonValue]’:
/usr/include/c++/9/bits/predefined_ops.h:43:23:   required from ‘constexpr bool __gnu_cxx::__ops::_Iter_less_iter::operator()(_Iterator1, _Iterator2) const [with _Iterator1 = __gnu_cxx::__normal_iterator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item*, std::vector<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item, std::allocator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item> > >; _Iterator2 = __gnu_cxx::__normal_iterator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item*, std::vector<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item, std::allocator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item> > >]’
/usr/include/c++/9/bits/stl_algo.h:81:17:   required from ‘void std::__move_median_to_first(_Iterator, _Iterator, _Iterator, _Iterator, _Compare) [with _Iterator = __gnu_cxx::__normal_iterator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item*, std::vector<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item, std::allocator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item> > >; _Compare = __gnu_cxx::__ops::_Iter_less_iter]’
/usr/include/c++/9/bits/stl_algo.h:1920:34:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item*, std::vector<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item, std::allocator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item> > >; _Compare = __gnu_cxx::__ops::_Iter_less_iter]’
/usr/include/c++/9/bits/stl_algo.h:1952:38:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item*, std::vector<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item, std::allocator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item> > >; _Size = long int; _Compare = __gnu_cxx::__ops::_Iter_less_iter]’
/usr/include/c++/9/bits/stl_algo.h:1967:25:   required from ‘void std::__sort(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item*, std::vector<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item, std::allocator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item> > >; _Compare = __gnu_cxx::__ops::_Iter_less_iter]’
/usr/include/c++/9/bits/stl_algo.h:4867:18:   required from ‘void std::sort(_RAIter, _RAIter) [with _RAIter = __gnu_cxx::__normal_iterator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item*, std::vector<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item, std::allocator<hazelcast::client::impl::LazyEntryArrayImpl<std::__cxx11::basic_string<char>, hazelcast::client::HazelcastJsonValue>::Item> > >]’
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/impl/EntryArrayImpl.h:56:30:   required from ‘void hazelcast::client::impl::EntryArrayImpl<K, V>::sort(hazelcast::client::query::IterationType, const hazelcast::util::Comparator<std::pair<const K*, const V*> >*) [with K = std::__cxx11::basic_string<char>; V = hazelcast::client::HazelcastJsonValue]’
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/map/ClientMapProxy.h:809:21:   required from ‘std::vector<V> hazelcast::client::map::ClientMapProxy<K, V>::values(hazelcast::client::query::PagingPredicate<K, V>&) [with K = std::__cxx11::basic_string<char>; V = hazelcast::client::HazelcastJsonValue]’
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/IMap.h:642:49:   required from ‘std::vector<V> hazelcast::client::IMap<K, V>::values(hazelcast::client::query::PagingPredicate<K, V>&) [with K = std::__cxx11::basic_string<char>; V = hazelcast::client::HazelcastJsonValue]’
/home/rikevoltz/work/Projects/hazelcast_tests/main.cpp:25:43:   required from here
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/impl/LazyEntryArrayImpl.h:226:47: error: no match for ‘operator<’ (operand types are ‘hazelcast::client::HazelcastJsonValue’ and ‘hazelcast::client::HazelcastJsonValue’)
  226 |                                 return *value < *rhs.value;
      |                                        ~~~~~~~^~~~~~~~~~~~
In file included from /home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/config/NearCacheConfig.h:29,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/ClientConfig.h:33,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/map/impl/ClientMapProxyFactory.h:20,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h:26,
                 from /home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/HazelcastClient.h:19,
                 from /home/rikevoltz/work/Projects/hazelcast_tests/main.cpp:1:
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/TypedData.h:83:28: note: candidate: ‘bool hazelcast::client::operator<(const hazelcast::client::TypedData&, const hazelcast::client::TypedData&)’
   83 |         bool HAZELCAST_API operator<(const TypedData &lhs, const TypedData &rhs);
      |                            ^~~~~~~~
/home/rikevoltz/.conan/data/hazelcast-cpp-client/3.12/_/_/package/49e7f59961e8ed9b7d1d33caa2e6d613b00b72a5/include/hazelcast/client/TypedData.h:83:55: note:   no known conversion for argument 1 from ‘hazelcast::client::HazelcastJsonValue’ to ‘const hazelcast::client::TypedData&’
   83 |         bool HAZELCAST_API operator<(const TypedData &lhs, const TypedData &rhs);
      |                                      ~~~~~~~~~~~~~~~~~^~~
```
The same situation with another type (string, int, etc.) compiles and works correctly. This is likely due to the missng `operator<` for `HazelcastJsonValue`.

#### Steps to reproduce the behaviour
  ```c++
  auto client = hazelcast::client::HazelcastClient{config};
  auto some_map = client.getMap<std::string, HazelcastJsonValue>("test_map");
  some_map.put("some_key", HazelcastJsonValue("{\"id\":\"some_id\"}"));
  some_map.put("some_other_key", HazelcastJsonValue("{\"id\":\"some_other_id\"}"));
  some_map.put("another_key", HazelcastJsonValue("{\"id\":\"another_id\"}"));
  auto predicate = PagingPredicate<std::string, HazelcastJsonValue>(2);
  auto results = some_map.values(predicate);
```

### PR DESCRIPTION
**Pull request by RikeVoltz**
fixes #589 
fixes #590

### CODE REVIEW

**Comment by ihsandemir** [comment]
verify

**Comment by RikeVoltz** [comment]
There are some issues with compiling current version of master branch of hazelcast-cpp-client by gcc 9.3 - especially [there](https://github.com/hazelcast/hazelcast-cpp-client/blob/5fc77d0c6ec863c8b9864c6537c9f5d352ed2f85/hazelcast/src/hazelcast/client/network.cpp#L911) - there is  `std::atomic<std::chrono::steady_clock::time_point> closedTime` variable in Connection class, that doesn't initialized explicitly in the constructor of this class. It entails compile error (because `atomic` default empty constructor is noexcept and it obligates internal variable to have noexcept default empty constructor too) in gcc<10 (in 10.0 everything is ok) and clang<9.0 (in 9 everything is ok) (probably in new versions of compilers they made time_point constructor noexcept). It can be fixed by using mutexes instead of atomic variable or by other solutions, provided [there](https://stackoverflow.com/a/29364778/12480542). Maybe it entailed failed linux build. Should I commit fixes, create new issue, or is there some other problem in build?

**Comment by ihsandemir** [comment]
The failing tests at linux 
```
AwsClientTest.testClientAwsMemberNonDefaultPortConfig
AwsClientTest.testClientAwsMemberWithSecurityGroupDefaultIamRole
AwsClientTest.testFipsEnabledAwsDiscovery
``` 
will be OK once we have the windows build machine up and running, we have a problem at AWS to make the windows up and running, otherwise the tests look as a pass.

**Comment by ihsandemir** [comment]
@RikeVoltz Regarding uninitialized `closedTime`, yes, we can set it to a some initial value less than or equal to the startTime and not print it if it is less equal to the start time. If this solves the compilation problem, then this would be preferable compared to mutex usage.

Please go ahead and open a new issue and submit a new PR for that as well.

Note: Test failure is not related to this and it is due to our windows build machine dependency in AWS tests and i am working to make that machine up and running again.

**Comment by RikeVoltz** [comment]
> The failing tests at linux
> 
> ```
> AwsClientTest.testClientAwsMemberNonDefaultPortConfig
> AwsClientTest.testClientAwsMemberWithSecurityGroupDefaultIamRole
> AwsClientTest.testFipsEnabledAwsDiscovery
> ```
> 
> will be OK once we have the windows build machine up and running, we have a problem at AWS to make the windows up and running, otherwise the tests look as a pass.

Ok, glad to hear it) But a little issue with failed compilation still exist (at least for me). Could you check it, please?

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
verify

**Pull request merged**
