### PR TITLE
Solved what is conflict with mysql-dev

### PR DESCRIPTION
**Pull request by skyend**
fixes https://github.com/hazelcast/hazelcast-cpp-client/issues/518 

I changed a member value name `PROTOCOL_VERSION` to `HAZELCAST_CLIENT_PROTOCOL_VERSION`

### CODE REVIEW

**Comment by skyend** [comment]
I fixed something that it rises conflict with other libraries such as Runnable in Poco 

I just make satisfied when compiling with other libraries by adding namespace hint.

**Comment by ihsandemir** [comment]
verify

**Comment by skyend** [comment]
@ihsandemir yes, please. thank you.  I glad to I have been contributing :)

**Comment by skyend** [comment]
@ihsandemir Excuse me, Could you tell me for how I merge my source?

**Comment by ihsandemir** [comment]
@skyend i think you maynot merge. i will merge it. did you send the signed form?

**Comment by skyend** [comment]
@ihsandemir I didn't know that i have to merge it, 
this is the first time for me contribute to Opensource Project. 
thank you for merge instead of me.
and.. yes, I sent to <cla@hazelcast.com> 😄

**Comment by ihsandemir** [comment]
> @ihsandemir I didn't know that i have to merge it,
> this is the first time for me contribute to Opensource Project.
> thank you for merge instead of me.
> and.. yes, I sent to [cla@hazelcast.com](mailto:cla@hazelcast.com) 😄

@skyend Are you sure that you sent the email to correct address, because we could not see it in the inbox? Can you double check and resend it if not sent and can you cc to my email ihsan@hazelcast.com so that I can follow up.

**Comment by ihsandemir** [comment]
verify

**Comment by ihsandemir** [comment]
@skyend I merged the PR. Thanks for the contribution.

**Comment by skyend** [comment]
@ihsandemir Thank you 😃

**Pull request merged**
