### PR TITLE
Solution for Issue #556 - Current logging implementation has limitations

### PR DESCRIPTION
**Pull request by sbrown-uhd**
PR to resolve the above issue in a later version of hazelcast C++ client with the provision of a LoggerCallback interface. This consists just of the code changes to implement the logging callback.

Please let me know if more changes are required or samples are needed for this case, documentation changes will also be required, so will be happy to provide necessary text.

### CODE REVIEW

**Comment by ihsandemir** [comment]
Hello @sbrown-uhd Thanks for the PR. 

I need to do a few things before we can verify this PR. I need to upgrade the compiler versions of the build environments (Linux, Windows and Mac) to support the C++11 (which we did not upgrade to stay binary compatible (ABI compatibility) to the oldest possible users. After this I will submit a PR to use the C++11 or later complier in cmake config. And then we can run your PR. This may take some time since environment upgrade may take time and we are very focused on 4.0 release of Java side as well. I will try to find some time to give this a priority. I will update you when ready and we can see how it works.

Meanwhile, in order to merge your pull request, we need you to sign [Hazelcast Contributor Agreement](https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement). Can you do that? You can just email the signed form.

**Comment by sbrown-uhd** [comment]
Hello @ihsandemir 

No problem at all, we have what we need working locally here (based on my PR) anyway, so as long as we know that at some point it will probably be merged to an official future version that's great. I understand this isn't simply a drop in solution given the current constraints of compiler versions etc.

I'll get the contributor agreement signed and returned shortly.

**Comment by ihsandemir** [comment]
Hello @sbrown-uhd We changed the logging config and impl significantly, can you double check if your PR still applies and if so update your PR? Thanks.

**Comment by ihsandemir** [comment]
Closing this PR since the issue was solved with the new logger implementation. Please re-open it if anything is missing. thanks.

**Pull request closed without merging**
