### PR TITLE
Assertion Failure is Fixed [API-1501]

### PR DESCRIPTION
**Pull request by hakanaktas0**
solves [this issue](https://github.com/hazelcast/hazelcast-cpp-client/issues/1005)

### CODE REVIEW

**Review by ihsandemir — COMMENTED** [review]
Can you add a test for the fix?

**Comment by ihsandemir** [comment]
verify

**Comment by hakanaktas0** [comment]
verify

**Comment by hakanaktas0** [comment]
Because TTL has to be an integer it can't be less than 1, 0 is infinite, I had to add 1 second sleep. Before the fix, this test would give an assertion error, should pass without problems after the fix.

**Review by ihsandemir — APPROVED** [review]

**Comment by OzanCansel** [comment]
I have reviewev the PR and here are my findings :

- Firstly, the fix is correct so it works.

But I don't think it is a good implementation because we call `emplace` function 3 times. Indeed, there is no need for that, it can be handled with only one emplace operation..

1. Add copy assingment special member function to the session_state class.
``` C++
    // cp_impl.h#96
    session_state& operator=(const session_state& rhs);
```
2. Make definition of it as :
``` C++
// cp_impl.cpp
proxy_session_manager::session_state&
proxy_session_manager::session_state::operator=(const session_state& rhs)
{
  id  = rhs.id;
  ttl = rhs.ttl;
  creation_time = rhs.creation_time;
  acquire_count = rhs.acquire_count.load();

  return *this;
}
```

3. Define `create_new_session` like this. If there is already an entry at the `sessions_` with the specified `group_id`, then just assign brand-new `session_state` to the `value` of it.

``` C++
   // the lock_ is already acquired as write lock
    auto response = request_new_session(group_id);
    session_state state { response.id , response.ttl_millis };

    auto result = sessions_.emplace( group_id, state );
    
    if(!result.second)
        result.first->second = state;

    schedule_heartbeat_task(response.heartbeat_millis);
    return result.first;
```

**Pull request merged**
